---
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - echo ${GITHUB_REF}
    - echo ${GITHUB_REF##*/}
    - echo -n ${GITHUB_REF##*/} > ${GITHUB_WORKSPACE}/version.txt

checksum:
  name_template: CHECKSUMS.txt

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^integration-test:'

builds:
#  - id: registry-lambda-yandex
#    dir: lambdas/yandex/registry-lambda-yandex
#    binary: registry-lambda-yandex
#    goos:
#      - linux
#    goarch:
#      - amd64

  - id: registry-lambda-aws
    dir: lambdas/aws/
    binary: registry-lambda-aws
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: lambda-aws
    builds:
      - registry-lambda-aws
    files:
      - version.txt
    format: zip
    name_template: "{{ .ProjectName }}-lambda-aws-{{ .Version }}"
    wrap_in_directory: false

#  - id: lambda-yandex
#    builds:
#      - registry-lambda-yandex
#    format: zip
#    name_template: "{{ .ProjectName }}-lambda-yandex-{{ .Version }}"
#    wrap_in_directory: false
